## This configuration was generated by terraform-provider-oci

resource oci_core_instance export_instance-public {
  agent_config {
    is_management_disabled = "false"
    is_monitoring_disabled = "false"
  }
  availability_config {
    recovery_action = "RESTORE_INSTANCE"
  }
  availability_domain = data.oci_identity_availability_domain.export_SXdD-US-ASHBURN-AD-1.name
  compartment_id      = var.compartment_ocid
  create_vnic_details {
    assign_public_ip = "true"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
      "Oracle-Tags.CreatedOn" = "2020-08-25T02:03:42.999Z"
    }
    display_name = "instance-public"
    freeform_tags = {
    }
    hostname_label = "instance-public"
    nsg_ids = [
    ]
    private_ip             = "10.100.0.2"
    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.export_Public-Subnet-vcngbu.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  #dedicated_vm_host_id = <<Optional value not found in discovery>>
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
    "Oracle-Tags.CreatedOn" = "2020-08-25T02:03:42.735Z"
  }
  display_name = "instance-public"
  extended_metadata = {
  }
  fault_domain = "FAULT-DOMAIN-1"
  freeform_tags = {
  }
  #ipxe_script = <<Optional value not found in discovery>>
  #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
  launch_options {
    boot_volume_type                    = "PARAVIRTUALIZED"
    firmware                            = "UEFI_64"
    is_consistent_volume_naming_enabled = "true"
    is_pv_encryption_in_transit_enabled = "false"
    network_type                        = "PARAVIRTUALIZED"
    remote_data_volume_type             = "PARAVIRTUALIZED"
  }
  metadata = {
    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFaWre7kqUVvv/pnzT6pswlaVNrxgNkWcM9vXJcVfNJWvFMPsCvrQLSW0zbDoLks5ZpBKyZfnWw5sIdB9rr3PRWyquwgAf+VojcYLe++DRlL1Lpwtz8jiR4XqhbJ0ZHZFOooHcpVGFLqX/vmIKdQuaEGqeZnHDWxZZHt4gI+s5SdK1IQ9KKc11CYx24nO8MoK8tDuff7xvsiIhF2kCptrbthkkDa6m8rFhgzAiF8TSFIOMWtKYtWa4xfPwRJjrfSYMfF9sO/9LYvKSnVCT1IlTT/08cYNSvxM3BJ9h19JmBHnuZUxKWQC00nBTfwV8BUVuCwcFlGGotgBRf84w2v6r tomel_000@m4700"
    "user_data"           = "IyEvYmluL2Jhc2gKCnl1bSB1cGRhdGUgLXkgCnl1bSBpbnN0YWxsIC15IGN1cmwgb3BlbnNzaC1zZXJ2ZXIgCmN1cmwgaHR0cHM6Ly90aW1zLm9yYWNsZWNsb3VkLmNvbS95dW0vaW5zdGFsbC5zaCB8IHN1ZG8gYmFzaAp5dW0gaW5zdGFsbCAteSBvc3NoLXNlcnZlciAKeXVtIGluc3RhbGwgLXkgbnNjZApzeXN0ZW1jdGwgZW5hYmxlIG5zY2QKc3lzdGVtY3RsIHN0YXJ0IG5zY2QgCgpnZXRlbnQgcGFzc3dkCg=="
  }
  #preserve_boot_volume = <<Optional value not found in discovery>>
  shape = "VM.Standard2.1"
  shape_config {
    ocpus = "1"
  }
  source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    #kms_key_id = <<Optional value not found in discovery>>
    source_id   = var.export_instance-20200824-2005_source_image_id
    source_type = "image"
  }
  state = "RUNNING"
}
resource oci_core_instance export_instance-20200824-2005 {
  agent_config {
    is_management_disabled = "false"
    is_monitoring_disabled = "false"
  }
  availability_config {
    recovery_action = "RESTORE_INSTANCE"
  }
  availability_domain = data.oci_identity_availability_domain.export_SXdD-US-ASHBURN-AD-2.name
  compartment_id      = var.compartment_ocid
  create_vnic_details {
    assign_public_ip = "false"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
      "Oracle-Tags.CreatedOn" = "2020-08-25T02:06:27.567Z"
    }
    display_name = "instance-20200824-2005"
    freeform_tags = {
    }
    hostname_label = "instance-20200824-2005"
    nsg_ids = [
    ]
    private_ip             = "10.100.1.2"
    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.export_Private-Subnet-vcngbu.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  #dedicated_vm_host_id = <<Optional value not found in discovery>>
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
    "Oracle-Tags.CreatedOn" = "2020-08-25T02:06:27.299Z"
  }
  display_name = "instance-20200824-2005"
  extended_metadata = {
  }
  fault_domain = "FAULT-DOMAIN-1"
  freeform_tags = {
  }
  #ipxe_script = <<Optional value not found in discovery>>
  #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
  launch_options {
    boot_volume_type                    = "PARAVIRTUALIZED"
    firmware                            = "UEFI_64"
    is_consistent_volume_naming_enabled = "true"
    is_pv_encryption_in_transit_enabled = "false"
    network_type                        = "PARAVIRTUALIZED"
    remote_data_volume_type             = "PARAVIRTUALIZED"
  }
  metadata = {
    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFaWre7kqUVvv/pnzT6pswlaVNrxgNkWcM9vXJcVfNJWvFMPsCvrQLSW0zbDoLks5ZpBKyZfnWw5sIdB9rr3PRWyquwgAf+VojcYLe++DRlL1Lpwtz8jiR4XqhbJ0ZHZFOooHcpVGFLqX/vmIKdQuaEGqeZnHDWxZZHt4gI+s5SdK1IQ9KKc11CYx24nO8MoK8tDuff7xvsiIhF2kCptrbthkkDa6m8rFhgzAiF8TSFIOMWtKYtWa4xfPwRJjrfSYMfF9sO/9LYvKSnVCT1IlTT/08cYNSvxM3BJ9h19JmBHnuZUxKWQC00nBTfwV8BUVuCwcFlGGotgBRf84w2v6r tomel_000@m4700"
    "user_data"           = "IyEvYmluL2Jhc2gKCnl1bSB1cGRhdGUgLXkgCnl1bSBpbnN0YWxsIC15IGN1cmwgb3BlbnNzaC1zZXJ2ZXIgCmN1cmwgaHR0cHM6Ly90aW1zLm9yYWNsZWNsb3VkLmNvbS95dW0vaW5zdGFsbC5zaCB8IHN1ZG8gYmFzaAp5dW0gaW5zdGFsbCAteSBvc3NoLXNlcnZlciAKeXVtIGluc3RhbGwgLXkgbnNjZApzeXN0ZW1jdGwgZW5hYmxlIG5zY2QKc3lzdGVtY3RsIHN0YXJ0IG5zY2QgCgpnZXRlbnQgcGFzc3dkCg=="
  }
  #preserve_boot_volume = <<Optional value not found in discovery>>
  shape = "VM.Standard2.1"
  shape_config {
    ocpus = "1"
  }
  source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    #kms_key_id = <<Optional value not found in discovery>>
    source_id   = var.export_instance-20200824-2005_source_image_id
    source_type = "image"
  }
  state = "RUNNING"
}
resource oci_core_internet_gateway export_Internet-Gateway-vcngbu {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
    "Oracle-Tags.CreatedOn" = "2020-08-25T01:55:39.471Z"
  }
  display_name = "Internet Gateway-vcngbu"
  enabled      = "true"
  freeform_tags = {
    "VCN" = "VCN-2020-08-25T01:54:52"
  }
  vcn_id = oci_core_vcn.export_vcngbu.id
}
resource oci_core_public_ip export_IP-for-NAT-gateway-ocid1-natgateway-oc1-iad-aaaaaaaaderc4ue6osadha4srohg4zivibqpvexzewiw7jb7od6ylaeo4wza {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
    "Oracle-Tags.CreatedOn" = "2020-08-25T01:55:41.109Z"
  }
  display_name = "IP for NAT gateway: ocid1.natgateway.oc1.iad.aaaaaaaaderc4ue6osadha4srohg4zivibqpvexzewiw7jb7od6ylaeo4wza"
  freeform_tags = {
    "VCN" = "VCN-2020-08-25T01:54:52"
  }
  lifetime = "EPHEMERAL"
  #private_ip_id = <<Optional value not found in discovery>>
}
resource oci_core_service_gateway export_Service-Gateway-vcngbu {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
    "Oracle-Tags.CreatedOn" = "2020-08-25T01:55:39.664Z"
  }
  display_name = "Service Gateway-vcngbu"
  freeform_tags = {
    "VCN" = "VCN-2020-08-25T01:54:52"
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = "ocid1.service.oc1.iad.aaaaaaaam4zfmy2rjue6fmglumm3czgisxzrnvrwqeodtztg7hwa272mlfna"
  }
  vcn_id = oci_core_vcn.export_vcngbu.id
}
resource oci_core_subnet export_Private-Subnet-vcngbu {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.100.1.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
    "Oracle-Tags.CreatedOn" = "2020-08-25T01:55:39.360Z"
  }
  dhcp_options_id = oci_core_vcn.export_vcngbu.default_dhcp_options_id
  display_name    = "Private Subnet-vcngbu"
  dns_label       = "sub08250155341"
  freeform_tags = {
    "VCN" = "VCN-2020-08-25T01:54:52"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_Route-Table-for-Private-Subnet-vcngbu.id
  security_list_ids = [
    oci_core_security_list.export_Security-List-for-Private-Subnet-vcngbu.id,
  ]
  vcn_id = oci_core_vcn.export_vcngbu.id
}
resource oci_core_subnet export_Public-Subnet-vcngbu {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.100.0.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
    "Oracle-Tags.CreatedOn" = "2020-08-25T01:55:39.286Z"
  }
  dhcp_options_id = oci_core_vcn.export_vcngbu.default_dhcp_options_id
  display_name    = "Public Subnet-vcngbu"
  dns_label       = "sub08250155340"
  freeform_tags = {
    "VCN" = "VCN-2020-08-25T01:54:52"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_vcngbu.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_vcngbu.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_vcngbu.id
}
resource oci_core_private_ip export_instance-20200824-2005_1 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
    "Oracle-Tags.CreatedOn" = "2020-08-25T02:06:27.567Z"
  }
  display_name = "instance-20200824-2005"
  freeform_tags = {
  }
  hostname_label = "instance-20200824-2005"
  ip_address     = "10.100.1.2"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljr5lk6mxdgoqugdrhdyz3ejc4ij6sfdbwmeu7otqidbixr665cnyiq"
}
resource oci_core_private_ip export_instance-public_1 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
    "Oracle-Tags.CreatedOn" = "2020-08-25T02:03:42.999Z"
  }
  display_name = "instance-public"
  freeform_tags = {
  }
  hostname_label = "instance-public"
  ip_address     = "10.100.0.2"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljshmlakfbjj5rckdjy4sb25vhiyq5rohrj5f4vqtvkkiympshqth3q"
}
resource oci_core_vcn export_vcngbu {
  cidr_block     = "10.100.0.0/16"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
    "Oracle-Tags.CreatedOn" = "2020-08-25T01:55:38.264Z"
  }
  display_name = "vcngbu"
  dns_label    = "vcngbu"
  freeform_tags = {
    "VCN" = "VCN-2020-08-25T01:54:52"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  #is_ipv6enabled = <<Optional value not found in discovery>>
}
resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-vcngbu {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
    "Oracle-Tags.CreatedOn" = "2020-08-25T01:55:38.264Z"
  }
  display_name = "Default DHCP Options for vcngbu"
  freeform_tags = {
    "VCN" = "VCN-2020-08-25T01:54:52"
  }
  manage_default_resource_id = oci_core_vcn.export_vcngbu.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "vcngbu.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}
resource oci_core_nat_gateway export_NAT-Gateway-vcngbu {
  block_traffic  = "false"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
    "Oracle-Tags.CreatedOn" = "2020-08-25T01:55:40.000Z"
  }
  display_name = "NAT Gateway-vcngbu"
  freeform_tags = {
    "VCN" = "VCN-2020-08-25T01:54:52"
  }
  vcn_id = oci_core_vcn.export_vcngbu.id
}
resource oci_core_route_table export_Route-Table-for-Private-Subnet-vcngbu {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
    "Oracle-Tags.CreatedOn" = "2020-08-25T01:55:39.639Z"
  }
  display_name = "Route Table for Private Subnet-vcngbu"
  freeform_tags = {
    "VCN" = "VCN-2020-08-25T01:54:52"
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_NAT-Gateway-vcngbu.id
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "all-iad-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.export_Service-Gateway-vcngbu.id
  }
  vcn_id = oci_core_vcn.export_vcngbu.id
}
resource oci_core_default_route_table export_Default-Route-Table-for-vcngbu {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
    "Oracle-Tags.CreatedOn" = "2020-08-25T01:55:38.264Z"
  }
  display_name = "Default Route Table for vcngbu"
  freeform_tags = {
    "VCN" = "VCN-2020-08-25T01:54:52"
  }
  manage_default_resource_id = oci_core_vcn.export_vcngbu.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_Internet-Gateway-vcngbu.id
  }
}
resource oci_core_security_list export_Security-List-for-Private-Subnet-vcngbu {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
    "Oracle-Tags.CreatedOn" = "2020-08-25T01:55:39.489Z"
  }
  display_name = "Security List for Private Subnet-vcngbu"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "VCN-2020-08-25T01:54:52"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.100.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.100.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_vcngbu.id
}
resource oci_core_default_security_list export_Default-Security-List-for-vcngbu {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/tom.eliason@oracle.com"
    "Oracle-Tags.CreatedOn" = "2020-08-25T01:55:38.264Z"
  }
  display_name = "Default Security List for vcngbu"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "VCN-2020-08-25T01:54:52"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.100.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_vcngbu.default_security_list_id
}
