## This configuration was generated by terraform-provider-oci

#data "oci_tenancy" {
#    tenancy_ocid="${var.tenancy_ocid}"
#}

data oci_identity_compartments tenancycompartments {
  compartment_id = "${var.tenancy_ocid}"
  filter {
    name = "name" 
    values ["GBU"]
  }
}

output "tenancycompartments" {
  description = "compartment" 
  value = oci_identity_compartments.tenancycompartments.id 
}


