## This configuration was generated by terraform-provider-oci

#resource oci_identity_dynamic_group TIMS-oSSH {
#  compartment_id = "${var.tenancy_ocid}"
#  description = "TIMS-oSSH"
#  freeform_tags = {}
#  matching_rule = "any {instance.compartment.id = /*/}"
#  name          = "TIMS-oSSH"
#}
 
resource oci_identity_policy TIMS-oSSH {
  compartment_id = var.tenancy_ocid
  description = "TIMS-oSSH"
  freeform_tags = {
  }
  name = "TIMS-oSSH"
  statements = [
    "allow dynamic-group TIMS-oSSH to inspect users in tenancy",
    "allow dynamic-group TIMS-oSSH to inspect groups in tenancy",
    "allow dynamic-group TIMS-oSSH to inspect identity-providers in tenancy",
  ]
}
