## This configuration was generated by terraform-provider-oci

data oci_identity_identity_providers OracleIdentityCloudService {
  compartment_id = "${var.tenancy_ocid}"
  protocol = "SAML2"
}

resource oci_identity_compartment INFRA {
  compartment_id = "${var.tenancy_ocid}"
  description = "INFRA"
  name = "INFRA"
}

#resource oci_identity_dynamic_group TIMS-oSSH {
#  compartment_id = "${var.tenancy_ocid}"
#  description = "TIMS-oSSH"
#  freeform_tags = {}
#  matching_rule = "any {instance.compartment.id = /*/}"
#  name          = "TIMS-oSSH"
#}

resource oci_identity_group INFRA {
  compartment_id = "${var.tenancy_ocid}"
  description = "INFRA"
  freeform_tags = {}
  name = "INFRA"
}


resource oci_identity_idp_group_mapping OracleIdentityCloudService_idp_group_mapping_7 {
  group_id             = "${oci_identity_group.INFRA.id}"
  identity_provider_id = "${data.oci_identity_identity_providers.OracleIdentityCloudService.identity_providers[0].id}"
  idp_group_name       = "INFRA"
}

resource oci_identity_policy INFRA {
  compartment_id = "${var.tenancy_ocid}"
  description = "INFRA"
  freeform_tags = {
  }
  name = "INFRA_Policy"
  statements = [
    "allow group INFRA to manage all-resources in compartment INFRA",
    "allow group INFRA to use tag-namespaces in tenancy",
    "allow group INFRA to manage repos in tenancy",
  ]
}

#resource oci_identity_policy TIMS-oSSH {
#  compartment_id = var.tenancy_ocid
#  description = "TIMS-oSSH"
#  freeform_tags = {
#  }
#  name = "TIMS-oSSH"
#  statements = [
#    "allow dynamic-group TIMS-oSSH to inspect users in tenancy",
#    "allow dynamic-group TIMS-oSSH to inspect groups in tenancy",
#    "allow dynamic-group TIMS-oSSH to inspect identity-providers in tenancy",
#  ]
#}
#resource oci_identity_policy TIMS-oSSH-Users {
#  compartment_id = var.tenancy_ocid
#  description = "TIMS-oSSH-Users"
#  freeform_tags = {
#  }
#  name = "TIMS-oSSH-Users"
#  statements = [
#    "allow group CMS to manage instances in compartment CMS",
#    "allow group CMS to use instances in compartment CMS",
#  ]
#}

#output "oci_identity_policy" {
#  description = "TIMS-oSSH-Users Policy"
#  value = oci_identity_policy.TIMS-oSSH-Users.id
  #value = oci_identity_policy.TIMS-oSSH.id
#}

output "oci_identity_compartment" {
  description = "compartment" 
  value = oci_identity_compartment.INFRA.id 
}

output "oci_identity_identity_provider" {
  description = "idp"
  value = data.oci_identity_identity_providers.OracleIdentityCloudService.identity_providers[0].id  
  #value = data.oci_identity_identity_providers.OracleIdentityCloudService.name
}


