## This configuration was generated by terraform-provider-oci

#data "oci_tenancy" {
#    tenancy_ocid="${var.tenancy_ocid}"
#}

data oci_identity_identity_providers OracleIdentityCloudService {
  compartment_id = "${var.tenancy_ocid}"
  protocol = "SAML2"
}

resource oci_identity_compartment GBU {
  compartment_id = "${var.tenancy_ocid}"
  description = "GBU"
  name = "GBU"
}

resource oci_identity_dynamic_group TIMS-oSSH {
  compartment_id = "${var.tenancy_ocid}"
  description = "TIMS-oSSH"
  freeform_tags = {}
  matching_rule = "any {instance.compartment.id = /*/}"
  name          = "TIMS-oSSH"
}

resource oci_identity_group GBU {
  compartment_id = "${var.tenancy_ocid}"
  description = "GBU"
  freeform_tags = {}
  name = "GBU"
}


resource oci_identity_idp_group_mapping OracleIdentityCloudService_idp_group_mapping_7 {
  group_id             = "${oci_identity_group.GBU.id}"
  identity_provider_id = "${data.oci_identity_identity_providers.OracleIdentityCloudService.identity_providers[0].id}"
  idp_group_name       = "GBU"
}

resource oci_identity_policy GBU_Policy {
  compartment_id = "${var.tenancy_ocid}"
  description = "GBU_Policy"
  freeform_tags = {
  }
  name = "GBU_Policy"
  statements = [
    "allow group GBU to manage all-resources in compartment GBU",
    "allow group GBU to use tag-namespaces in tenancy",
    "allow group GBU to manage repos in tenancy",
  ]
}

resource oci_identity_policy TIMS-oSSH {
  compartment_id = var.tenancy_ocid
  description = "TIMS-oSSH"
  freeform_tags = {
  }
  name = "TIMS-oSSH"
  statements = [
    "allow dynamic-group TIMS-oSSH to inspect users in tenancy",
    "allow dynamic-group TIMS-oSSH to inspect groups in tenancy",
    "allow dynamic-group TIMS-oSSH to inspect identity-providers in tenancy",
  ]
}
resource oci_identity_policy TIMS-oSSH-Users {
  compartment_id = var.tenancy_ocid
  description = "TIMS-oSSH-Users"
  freeform_tags = {
  }
  name = "TIMS-oSSH-Users"
  statements = [
    "allow group GBU to manage instances in compartment GBU",
    "allow group GBU to use instances in compartment GBU",
  ]
}

output "oci_identity_policy" {
  description = "TIMS-oSSH-Users Policy"
  value = oci_identity_policy.TIMS-oSSH-Users.id
  #value = oci_identity_policy.TIMS-oSSH.id
}

output "oci_identity_compartment" {
  description = "compartment" 
  value = oci_identity_compartment.GBU.id 
}

output "oci_identity_identity_provider" {
  description = "idp"
  value = data.oci_identity_identity_providers.OracleIdentityCloudService.identity_providers[0].id  
  #value = data.oci_identity_identity_providers.OracleIdentityCloudService.name
}


