## This configuration was generated by terraform-provider-oci

data oci_identity_compartments tenancycompartments {
  compartment_id = "${var.tenancy_ocid}"
  filter {
    name = "name" 
    values = ["GBU"]
  }
}

output "tenancycompartments" {
  description = "compartment" 
  value = data.oci_identity_compartments.tenancycompartments.compartments[0].id 
}


